### ISSUE TITLE
안녕하세요 강의를 보면서 Vue에 대해 학습하고 있습니다~ 한가지 질문드리고 싶어 Issue 남깁니다

### ISSUE THREAD

**Issue by S-Onix** [HeropCode/Vue-Todo-app#12]
터미널에서 webpack --mode production 이후

vue 파일의 template 태그와 script 태그는 정상적으로 동작되는 것을 확인했습니다

그런데 style 태그는 인식이 안되는 문제가 발생합니다...

처음에는 노드모듈이 정상적으로 설치되어있지 않는지 의심해서 재설치 이후 다시 빌드 후 실행했으니 여전히 같은 문제를 가지고 있습니다

package.json 파일의 설정은 

"devDependencies": {
    "@babel/core": "^7.10.5",
    "@babel/preset-env": "^7.10.4",
    "babel-loader": "^8.1.0",
    "css-loader": "^4.0.0",
    "postcss-loader": "^3.0.0",
    "vue-loader": "^15.9.3",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^4.44.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^5.0.9"
  },

와 같이 되어있습니다. 혹시 제가 놓친부분이 있다면 어느부분을 살펴보는게 좋을지... 질문드립니다

**Comment by S-Onix** [comment]
> 터미널에서 webpack --mode production 이후
> 
> vue 파일의 template 태그와 script 태그는 정상적으로 동작되는 것을 확인했습니다
> 
> 그런데 style 태그는 인식이 안되는 문제가 발생합니다...
> 
> 처음에는 no 정상적으로 설치되어있지 않는지 의심해서 재설치 이후 다시 빌드 후 실행했으니 여전히 같은 문제를 가지고 있습니다
> 
> package.json 파일의 설정은
> 
> "devDependencies": {
> "@babel/core": "^7.10.5",
> "@babel/preset-env": "^7.10.4",
> "babel-loader": "^8.1.0",
> "css-loader": "^4.0.0",
> "postcss-loader": "^3.0.0",
> "vue-loader": "^15.9.3",
> "vue-style-loader": "^4.1.2",
> "vue-template-compiler": "^2.6.11",
> "webpack": "^4.44.0",
> "webpack-cli": "^3.3.12",
> "webpack-dev-server": "^3.11.0",
> "webpack-merge": "^5.0.9"
> },
> 
> 와 같이 되어있습니다. 혹시 제가 놓친부분이 있다면 어느부분을 살펴보는게 좋을지... 질문드립니다

**Comment by S-Onix** [comment]
> 터미널에서 webpack --mode production 이후
> 
> vue 파일의 template 태그와 script 태그는 정상적으로 동작되는 것을 확인했습니다
> 
> 그런데 style 태그는 인식이 안되는 문제가 발생합니다...
> 
> 처음에는 노드모듈이 정상적으로 설치되어있지 않는지 의심해서 재설치 이후 다시 빌드 후 실행했으니 여전히 같은 문제를 가지고 있습니다
> 
> package.json 파일의 설정은
> 
> "devDependencies": {
> "@babel/core": "^7.10.5",
> "@babel/preset-env": "^7.10.4",
> "babel-loader": "^8.1.0",
> "css-loader": "^4.0.0",
> "postcss-loader": "^3.0.0",
> "vue-loader": "^15.9.3",
> "vue-style-loader": "^4.1.2",
> "vue-template-compiler": "^2.6.11",
> "webpack": "^4.44.0",
> "webpack-cli": "^3.3.12",
> "webpack-dev-server": "^3.11.0",
> "webpack-merge": "^5.0.9"
> },
> 
> 와 같이 되어있습니다. 혹시 제가 놓친부분이 있다면 어느부분을 살펴보는게 좋을지... 질문드립니다

**Comment by ParkYoungWoong** [comment]
안녕하세요.
답장이 늦어서 죄송합니다.
알려주신 package.json 내용만으론 문제 확인이 어렵지만,
현재 의심이 가는 부분은 webpack.config.js의 Style 관련 설정입니다.
확인해 보시고 여전히 문제가 해결되지 않는다면, 
프로젝트를 깃헙에 업로드 후 알려주시면 확인해 보겠습니다.
