### ISSUE TITLE
스타일 미적용 이슈 관련 문의드립니다.

### ISSUE THREAD

**Issue by sannimdev** [HeropCode/Vue-Todo-app#15]
안녕하세요.
패스트캠퍼스를 통해 강의를 잘 보고 있습니다.
그런데 스타일이 전혀 적용되지 않는 이슈로 문의드리게 되었습니다.
제가 아래의 링크에서 Github 저장소에 작성하며 공부하고 있는데요.
webpack.config.js를 아무리 살펴봐도 강사님께서 작성하신 부분과 CSS, SCSS부분에 차이가 없다고 생각되는데
테스트코드를 작성해서 다음과 같은 스타일 적용을 시도하여도 결과물 페이지에서는 모든 스타일 정의가 누락됩니다.
확인 부탁드립니다. 😥
```css
*{color:red};
```
[Github 학습 저장소](https://github.com/sannimdev/vue-fastcampus-all-in-one/tree/master/vue-03-todo)

**Comment by ParkYoungWoong** [comment]
우선 늦은 답변에 정말 죄송합니다ㅜㅠ
따로 알림 확인을 못해서 남겨주신 이슈를 오늘 아침에 확인습니다.
다시 한번 죄송합니다.

질문하신 내용에 대해선 관련 이슈가 아직 열려있습니다.
https://github.com/vuejs/vue-style-loader/issues/46

해당 내용을 정리하자면,
`css-loader` 모듈이 4버전으로 설치되면서, `vue-style-loader`와 충돌이 발생한 것으로 보입니다.
`css-loader`가 3에서 4버전으로 변경되면서, `esModule` 옵션의 기본값이 `true`로 변경되었습니다.

따라서 `css-loader`를 다음과 같이 3버전으로 설치하시거나,

```bash
$ npm i css-loader@3
```

혹은 `webpack.config.js` 설정에서 `css-loader` 옵션을 추가할 수 있습니다.
`test: /\.scss$/,` 부분도 같은 방법으로 옵션을 추가하면 됩니다.

```js
{
  test: /\.css$/,
  use: [
    'vue-style-loader',
    {
      loader: 'css-loader',
      options: { esModule: false }
    },
    'postcss-loader'
  ]
}
```
