### ISSUE TITLE
app.js 질문

### ISSUE THREAD

**Issue by woolarinet** [HeropCode/Vue-Todo-app#17]
패스트캠프 사이트에서 선생님의 Vue 올인원 수업을 듣는 학생입니다.

App.vue의 style태그 미인식현상이 주 문제였는데 밑의 같은 질문을 보고 해결하였습니다.

그 외의 질문은, main.js에서 console.log('Hello Vue') 라고 쓰고 webpack --mode production을 돌리면 app.js에 선생님 영상처럼 로그가 뜨는게 아닌, 단지 console.log("Hello Vue"); 이렇게만 뜹니다.

마지막으로 webpack --mode production 을 실행할 때마다 app.js의 길이가 계속 길어집니다. 전의 결과물들을 계속 저장한상태로 더해지는 것 같은데 이 또한 원인을 모르겠습니다. dist폴더를 삭제하고 다시 명령어를 실행해 생성이 되어도 app.js는 점점 더 길어져만 갑니다.

저의 깃헙의 Vue_Prac 안의 Vue_error폴더 안에 제 코드와 스크린샷을 올렸으니 참고해주시면 감사하겠습니다.
저의 노드는 12.19.0이며 npm은 6.14.8 입니다.
감사합니다.

**Comment by woolarinet** [comment]
추가로, dist 생성 시 안에 자동으로 생성되는 index.html 파일이 작동은 정상적으로 되지만, 
태그들이 문단띄기 적용없이 그냥 모든코드가 1번째 줄에 한줄로 쫙 표시가 되는 현상은 원인을 알 수 있을까요?

**Comment by ParkYoungWoong** [comment]
@woolarinet 님 안녕하세요.
해당 내용 확인하고 답변드려요~

우선, 처음 질문하신 `main.js`에서의 로그가 뜨는 내용은 제가 이해하질 못했습니다.
혹시 어떤 내용인지 좀 더 자세하게 설명해 주실 수 있을까요?

번들 결과인 `app.js`가 점점 길어지는 현상은 깃헙 내용만으론 재현하질 못했습니다.
혹시 예를 들어 100줄짜리 코드가 200줄이 되고 300줄이 되는 것처럼 계속 늘어난다는 의미인가요?

마지막으로 번들 결과의 `index.html`이 '난독화'되는 현상은 `html-webpack-plugin` 패키지의 버전 차이로 발생하는 현상입니다.
보통 최종 제품으로 웹 사이트를 배포할 때는 대부분의 코드를 압축하고 해석하기 어렵게 '난독화'를 하게 되는데요.
제가 강의에서 사용한 3버전이 아닌 최신 4버전으로 설치되면서 난독화가 기본값이 되었네요.
3버전으로 설치하시거나 다음과 같이 `minify` 옵션으로 난독화를 해제할 수 있습니다.

```js
new HtmlWebpackPlugin({
  template: path.join(__dirname, 'index.html'),
  minify: false
})
```

현재 `webpack`은 5버전, `webpack-cli`는 4버전으로 설치되어 있는데,
제가 강의에서 사용한 버전은 `webpack`이 4버전, `webpack-cli`가 3버전입니다.
혹시 제가 파악하지 못한 위 2개 질문도 여러 패키지의 버전 차이에서 발생하는 문제이지 않을까 추측해 봅니다.
가장 좋은 방법은 진행하시는 프로젝트의 `package.json`에 있는 내용을 실제 예제의 `package.json`에 있는 각 패키지 버전으로 설치하시는 겁니다.
쉽게 진행하는 방법은 실제 예제의 `package.json`의 `"devDependencies"`내용에서 필요한 항목들을 복사해서 붙여넣고 터미널에서 `npm install`을 입력하면 자동으로 내용에 맞게 추가/수정/삭제됩니다.

만약 위 문제들에 대한 좀 더 자세한 설명을 필요로 하시면,
thesecon@gmail.com로 연락주세요. 
최후에는 원격 제어로 문제 파악과 해결을 도와드릴 수 있습니다.

**Comment by woolarinet** [comment]
질문내용 정리해서 메일 혹은 이슈에 다시 말씀드리겠습니다!
