### ISSUE TITLE
[error] zsh: command not found: webpack

### ISSUE THREAD

**Issue by sgpark94** [HeropCode/Vue-Todo-app#21]
안녕하세요 강사님~!
공부하다가 ‎안되는 것이 생겼는데, ‎찾아보다가 막혀서 문의드립니다.

[에러사항]
$ webpack --mode production 입력시       
zsh: command not found: webpack가 뜹니다..ㅠ.ㅠ

참고 url : https://jcon.tistory.com/156
=> package.json 부분 scripts 쪽에 "webpack": "webpack" 추가후 npm run webpack 작성하니 dist 폴더안에 app.js가 생성되었습니다.

**Comment by ParkYoungWoong** [comment]
@sgpark94 님 안녕하세요.

터미널에서 바로 `wepback` 명령을 동작하지 마시고,
다음과 같이 package.json 파일의 scripts 옵션에 등록해서 `npm run build` 로 사용하세요.

```json
"scripts": {
  "dev": "webpack-dev-server --mode development",
  "build": "webpack --mode production",
  "lint": "eslint --ext .js,.vue .",
  "lint:fix": "eslint --fix --ext .js,.vue ."
},
```

기타 내용은 '자주 묻는 질문'으로 저장소 README.md 중간에 작성해 뒀으니 참고하세요.
https://github.com/HeropCode/Vue-Todo-app#webpack-%EC%82%AC%EC%9A%A9-%EC%8B%9C-%EC%9E%90%EC%A3%BC-%EB%AC%BB%EB%8A%94-%EC%A7%88%EB%AC%B8
